config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }
  devise_scope :user do
    scope module: :users do
      resource :profile, only: [:show, :edit, :update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "mains#index"
  resources :articles, except: [:show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :reactions, only: [:create]

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint(8)        not null, primary key
#  user_id    :bigint(8)
#  body       :text(65535)
#  deleted_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_comments_on_deleted_at  (deleted_at)
#  index_comments_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Comment < ApplicationRecord
  include BelongsToUserModule

  acts_as_paranoid

  has_many :article_comments, dependent: :destroy
  has_many :articles, through: :article_comments
  has_many :reactions, as: :reactionable, inverse_of: :reactionable, dependent: :destroy
  has_many :active_reactions, -> { Reaction.active }, as: :reactionable, class_name: 'Reaction', dependent: :destroy

  delegate :display_name, to: :user, allow_nil: true

  validates :body, presence: true, length: { maximum: 65535 }

  scope :latest, -> { order(created_at: :desc) }

  def grouped_active_reactions
    active_reactions.select('reactions.id, reactions.code, count(reactions.code) as reaction_count').group(:code)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_comment, only: [:destroy]

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    article = Article.find(params[:article_id])
    article_comment = @comment.article_comments.build
    article_comment.article = article
    respond_to do |format|
      if @comment.save
        format.html { render json: { article_id: article.id, body: render_to_string(partial: 'comments/index', collection: article.comments.latest, as: :comment), status: :created }.to_json }
      else
        format.html { render :new }
        format.json { render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    article = Article.find(params[:article_id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to (request.referer.presence || root_path), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :body)
    end
end

app/views/comments/_form.html.erb
<%= form_with(scope: :comment, url: article_comments_path(article), class: 'form-inline my-2 my-lg-0 comment-form disabled-default-ajax-form', local: false) do |form| %>
  <%= form.hidden_field :user_id, value: user.try(:id) %>
  <%= form.text_area :body, class: 'form-control' %>
  <%= form.submit(value: 'コメントする', class: 'btn btn-primary', data: {disable_with: '投稿中...'}) %>
<% end %>

app/views/comments/_index.html.erb
<div class="list-group-item list-group-item-action pr-0">
  <div class="d-flex w-100 justify-content-end align-items-center">
    <small><%= comment.created_at.strftime('%F %H:%M')%></small>
    <%= link_to_if comment.is_mine?(current_user), '<i class="fa fa-lg fa-trash-o ml-1 text-danger" aria-hidden="true"></i>'.html_safe, article_comment_path(comment.articles.first, comment), method: :delete, data: { confirm: '削除しますか？', dismiss: 'alert' }, class: 'ml-2' %>
  </div>
  <p class="mb-1">
    <%= simple_format comment.body %>
  </p>
  <small class="float-right"><%= comment.display_name %></small>
</div>