config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }
  devise_scope :user do
    scope module: :users do
      resource :profile, only: [:show, :edit, :update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "mains#index"
  resources :articles, except: [:show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :reactions, only: [:create]

end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

  before_action :authenticate_user!

  # POST /reactions
  # POST /reactions.json
  def create
    @reaction = Reaction.create_with(code: reaction_params[:code]).find_or_create_by(reaction_params.merge!({ user: current_user }))
    if @reaction.toggle!(:registered)
      render json: {
        reactionable_id: @reaction.reactionable_id,
        reactionable_type: @reaction.reactionable_type,
        body: render_to_string(partial: 'reactions/reaction_list', collection: @reaction.reactionable.grouped_active_reactions, as: :grouped_reaction),
        status: :created
      }.to_json
    else
      format.json { render json: { errors: @reaction.errors.full_messages }, status: :unprocessable_entity }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def reaction_params
      params.require(:reaction).permit(:code, :reactionable_type, :reactionable_id)
    end
end

app/views/reactions/_form.html.erb
<%= form_with(scope: :reaction, url: reactions_path, class: 'reaction-form disabled-default-ajax-form mb-0', local: false) do |form| %>
  <%= form.hidden_field :reactionable_type, value: reactionable.class.name %>
  <%= form.hidden_field :reactionable_id, value: reactionable.id %>

  <div class="d-flex justify-content-between align-items-center mt-1">
    <%= button_tag name: 'reaction[code]', value: :thumbs_up, class: 'reaction-action' do %>
      <%= image_pack_tag 'media/images/emoji/unicode/1f44d.png', title: 'thumbs_up', class: 'reaction-icon' %>
    <% end %>
    <%= button_tag name: 'reaction[code]', value: :thumbs_down, class: 'reaction-action' do %>
      <%= image_pack_tag 'media/images/emoji/unicode/1f44e.png', title: 'thumbs_down', class: 'reaction-icon' %>
    <% end %>
    <%= button_tag name: 'reaction[code]', value: :heart, class: 'reaction-action' do %>
      <%= image_pack_tag 'media/images/emoji/unicode/2764.png', title: 'heart', class: 'reaction-icon' %>
    <% end %>
    </div>
    <div class="d-flex justify-content-between align-items-center mt-3">
    <%= button_tag name: 'reaction[code]', value: :exclamation, class: 'reaction-action' do %>
      <%= image_pack_tag 'media/images/emoji/unicode/2757.png', title: 'exclamation', class: 'reaction-icon' %>
    <% end %>
    <%= button_tag name: 'reaction[code]', value: :question, class: 'reaction-action' do %>
      <%= image_pack_tag 'media/images/emoji/unicode/2753.png', title: 'question', class: 'reaction-icon' %>
    <% end %>
    <%= button_tag name: 'reaction[code]', value: :interrobang, class: 'reaction-action' do %>
      <%= image_pack_tag 'media/images/emoji/unicode/2049.png', title: 'interrobang', class: 'reaction-icon' %>
    <% end %>
  </div>
<% end %>

app/views/reactions/_reaction_area.html.erb
<div class="reaction-area d-flex">
  <a tabindex="0" class="reaction-icon-action text-dark" role="button" data-toggle="popover" data-trigger="focus" title="add reactions" data-placement="top" data-custom_id="<%= "reaction-list-#{reactionable.class.name}-#{reactionable.id}" %>">
    <i class="material-icons">sentiment_satisfied_alt</i>
  </a>
  <div class="" id="<%= "reaction-result-list-#{reactionable.class.name}-#{reactionable.id}" %>">
    <%= render partial: 'reactions/reaction_list', collection: reactionable.grouped_active_reactions, as: :grouped_reaction %>
  </div>

  <div id="<%= "reaction-list-#{reactionable.class.name}-#{reactionable.id}" %>" class="d-none">
    <%= render partial: 'reactions/form', locals: {reactionable: reactionable} %>
  </div>
</div>

app/views/reactions/_reaction_list.html.erb
<span class="p-1">
  <%= image_pack_tag grouped_reaction.emoji_image_path, class: 'reaction-icon' %>
  <span class="badge badge-pill badge-info"><%= grouped_reaction.reaction_count %></span>
</span>